/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "primary": "#DD3333",
              "primary-container": "#b9151e",
              "on-primary": "#ffffff",
              "on-primary-container": "#fffeff",
              "primary-fixed": "#ffdad6",
              "primary-fixed-dim": "#ffb3ac",
              "secondary": "#5e5e5c",
              "secondary-container": "#e1dfdc",
              "on-secondary": "#ffffff",
              "tertiary": "#43AD48",
              "tertiary-container": "#148828",
              "on-tertiary": "#ffffff",
              "on-background": "var(--on-background)",
              "surface-container-highest": "var(--surface-container-highest)",
              "surface-variant": "var(--surface-container-highest)",
              "on-surface-variant": "var(--on-surface-variant)",
              "surface-bright": "var(--surface-container-lowest)",
              "surface-container-lowest": "var(--surface-container-lowest)",
              "outline": "var(--outline)",
              "error": "#ba1a1a",
              "surface-container": "var(--surface-container)",
              "error-container": "#ffdad6",
              "outline-variant": "var(--outline-variant)",
              "on-error": "#ffffff",
              "surface-container-low": "var(--surface-container-low)",
              "surface": "var(--surface)",
              "deep-black": "#1d1b1a",
              "surface-container-high": "var(--surface-container-high)",
              "inverse-on-surface": "var(--inverse-on-surface)",
              "surface-tint": "#b9151e",
              "on-surface": "var(--on-surface)",
              "surface-dim": "var(--surface-container-high)",
              "inverse-surface": "var(--inverse-surface)",
              "background": "var(--background)",
              "white": "#FFFFFF",
              "cafe-cream": "#FDFBF7",
              "berry-red": "#DD3333",
              "sage-green": "#43AD48",
              "gold-yellow": "#F2B705",
              "paper-white": "#FFFFFF"
      },
      "borderRadius": {
              "sm": "0.25rem",
              "DEFAULT": "0.5rem",
              "md": "0.75rem",
              "lg": "1rem",
              "xl": "1.5rem",
              "full": "9999px"
      },
      "boxShadow": {
              "tactile": "0 4px 20px rgba(51, 49, 48, 0.05)",
              "tactile-hover": "0 8px 30px rgba(51, 49, 48, 0.09)",
      },
      "spacing": {
              "margin-desktop": "40px",
              "section-gap-md": "48px",
              "section-gap-lg": "80px",
              "margin-mobile": "16px",
              "gutter": "24px",
              "base": "8px",
              "container-max-width": "1200px"
      },
      "fontFamily": {
              "headline-md": ["Literata", "Georgia", "serif"],
              "headline-lg": ["Literata", "Georgia", "serif"],
              "body-md": ["Plus Jakarta Sans", "sans-serif"],
              "body-sm": ["Plus Jakarta Sans", "sans-serif"],
              "label-md": ["Plus Jakarta Sans", "sans-serif"],
              "label-lg": ["Plus Jakarta Sans", "sans-serif"],
              "body-lg": ["Plus Jakarta Sans", "sans-serif"],
              "headline-xl": ["Literata", "Georgia", "serif"],
              "headline-lg-mobile": ["Literata", "Georgia", "serif"]
      }
    },
  },
  plugins: [],
}
