/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "primary-fixed": "#ffdad4",
              "secondary-fixed-dim": "#73dd71",
              "on-background": "#1c1b1a",
              "on-primary-fixed-variant": "#930000",
              "surface-container-highest": "#e5e2df",
              "surface-variant": "#e5e2df",
              "on-surface-variant": "#5e3f3a",
              "tertiary-container": "#0052f9",
              "tertiary-fixed-dim": "#b7c4ff",
              "surface-bright": "#fdf9f6",
              "on-secondary": "#ffffff",
              "on-tertiary": "#ffffff",
              "surface-container-lowest": "#ffffff",
              "outline": "#926e69",
              "error": "#ba1a1a",
              "surface-container": "#f1edea",
              "on-primary-container": "#ffdad4",
              "on-secondary-fixed": "#002203",
              "error-container": "#ffdad6",
              "on-primary-fixed": "#410000",
              "on-secondary-fixed-variant": "#005312",
              "secondary-container": "#8cf888",
              "on-tertiary-container": "#dce1ff",
              "outline-variant": "#e8bdb6",
              "on-error": "#ffffff",
              "surface-container-low": "#f7f3f0",
              "primary-fixed-dim": "#ffb4a8",
              "surface": "#fdf9f6",
              "deep-black": "#000000",
              "surface-container-high": "#ebe7e4",
              "primary": "#9e0000",
              "secondary-fixed": "#8ffa8a",
              "inverse-on-surface": "#f4f0ed",
              "surface-tint": "#c00000",
              "tertiary": "#003ec2",
              "secondary": "#006e1a",
              "on-tertiary-fixed": "#001551",
              "on-error-container": "#93000a",
              "on-surface": "#1c1b1a",
              "surface-dim": "#ddd9d6",
              "primary-container": "#cc0000",
              "inverse-surface": "#31302f",
              "inverse-primary": "#ffb4a8",
              "tertiary-fixed": "#dce1ff",
              "background": "#fdf9f6",
              "white": "#FFFFFF",
              "on-secondary-container": "#00731c",
              "on-primary": "#ffffff",
              "on-tertiary-fixed-variant": "#0039b4"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "margin-desktop": "32px",
              "section-gap-md": "48px",
              "section-gap-lg": "80px",
              "margin-mobile": "16px",
              "gutter": "24px",
              "base": "8px",
              "container-max-width": "1200px"
      },
      "fontFamily": {
              "headline-md": ["Montserrat"],
              "headline-lg": ["Montserrat"],
              "body-md": ["Open Sans"],
              "body-sm": ["Open Sans"],
              "label-md": ["Open Sans"],
              "label-lg": ["Open Sans"],
              "body-lg": ["Open Sans"],
              "headline-xl": ["Montserrat"],
              "headline-lg-mobile": ["Montserrat"]
      },
      "fontSize": {
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "label-md": ["12px", {"lineHeight": "16px", "fontWeight": "700"}],
              "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
              "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-sm": ["12px", {"lineHeight": "14px", "letterSpacing": "0.03em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
