<#
.SYNOPSIS
    PowerShell Setup & Test Script for Hausbibliothek Microsoft 365 Email Integration via Power Automate.

.DESCRIPTION
    This script provides:
    1. The exact Power Automate / Logic App JSON Flow Definition (HTTP Webhook -> M365 Outlook Send Email V2).
    2. Interactive testing utility to send a test email via the Webhook URL.
    3. Configuration helper to write the Webhook URL directly to the backend .env configuration.

.PARAMETER WebhookUrl
    The HTTPS Webhook URL generated by Power Automate / Azure Logic Apps.

.PARAMETER Recipient
    Test recipient email address (default: bibliothek@sprachcafe-polnisch.org).

.EXAMPLE
    .\setup-powerautomate-mail.ps1 -WebhookUrl "https://prod-00.westeurope.logic.azure.com:443/workflows/..." -Recipient "bibliothek@sprachcafe-polnisch.org"
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory = $false)]
    [string]$WebhookUrl,

    [Parameter(Mandatory = $false)]
    [string]$Recipient = "bibliothek@sprachcafe-polnisch.org",

    [Parameter(Mandatory = $false)]
    [switch]$ConfigureServer
)

Write-Host "=================================================================" -ForegroundColor Cyan
Write-Host "📚 HAUSBIBLIOTHEK (hausbibliothek.org) - M365 POWER AUTOMATE SETUP" -ForegroundColor Green
Write-Host "=================================================================" -ForegroundColor Cyan
Write-Host ""

# -------------------------------------------------------------
# 1. FLOW DEFINITION & TRIGGER SCHEMA (JSON)
# -------------------------------------------------------------
$FlowJsonSchema = @'
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "to": {
      "type": "string",
      "description": "Recipient email address"
    },
    "from": {
      "type": "string",
      "description": "Sender address (e.g. bibliothek@sprachcafe-polnisch.org)"
    },
    "subject": {
      "type": "string",
      "description": "Email subject"
    },
    "bodyHtml": {
      "type": "string",
      "description": "Full responsive HTML email content"
    },
    "template": {
      "type": "string",
      "description": "Template identifier (welcome, loan_confirmation, due_reminder, etc.)"
    },
    "source": {
      "type": "string",
      "description": "Originating application domain"
    },
    "timestamp": {
      "type": "string"
    },
    "metadata": {
      "type": "object"
    }
  },
  "required": [
    "to",
    "subject",
    "bodyHtml"
  ]
}
'@

Write-Host "[1/3] Power Automate Flow Setup Anleitung:" -ForegroundColor Yellow
Write-Host "1. Öffne https://make.powerautomate.com/ (mit dem M365 Admin-Account des SprachCafés)."
Write-Host "2. Erstelle einen neuen 'Instant Cloud Flow' (Automatisierter Cloud-Flow)."
Write-Host "3. Trigger auswählen: 'When an HTTP request is received' (Beim Empfang einer HTTP-Anforderung)."
Write-Host "4. 'Request Body JSON Schema' einfügen (Schema siehe unten oder im Skript)."
Write-Host "5. Neue Aktion hinzufügen: 'Send an email (V2) - Office 365 Outlook' (E-Mail senden V2)."
Write-Host "   - To (An):            Trigger-Ausgabe 'to'"
Write-Host "   - Subject (Betreff):   Trigger-Ausgabe 'subject'"
Write-Host "   - Body (Textkörper):  Trigger-Ausgabe 'bodyHtml' (HTML-Modus aktiviert)"
Write-Host "   - From (Senden als):  bibliothek@sprachcafe-polnisch.org (oder Standard-Konto)"
Write-Host "6. Speichern und die generierte 'HTTP POST URL' kopieren."
Write-Host ""

# -------------------------------------------------------------
# 2. INTERACTIVE INPUT IF NOT PROVIDED
# -------------------------------------------------------------
if (-not $WebhookUrl) {
    Write-Host "Möchtest du eine Webhook-URL jetzt testen und konfigurieren?" -ForegroundColor Yellow
    $WebhookUrl = Read-Host "Power Automate Webhook URL eingeben (oder Enter zum Überspringen)"
}

if ($WebhookUrl -and $WebhookUrl.StartsWith("http")) {
    Write-Host ""
    Write-Host "[2/3] Sende Test-E-Mail über Power Automate Webhook..." -ForegroundColor Cyan

    $TestPayload = @{
        to = $Recipient
        from = "bibliothek@sprachcafe-polnisch.org"
        subject = "🧪 Test E-Mail: Hausbibliothek M365 Power Automate Integration"
        bodyHtml = @"
        <div style='font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #8B263E; border-radius: 12px; overflow: hidden;'>
            <div style='background-color: #8B263E; color: white; padding: 16px; text-align: center;'>
                <h2 style='margin: 0;'>📚 SprachCafé Polnisch - Hausbibliothek</h2>
            </div>
            <div style='padding: 20px; color: #333;'>
                <p>Hallo Bibliotheksteam,</p>
                <p>diese Test-E-Mail bestätigt, dass die <strong>Power Automate M365 Exchange Schnittstelle</strong> für <code>https://hausbibliothek.org/</code> erfolgreich eingerichtet wurde!</p>
                <p style='color: #8B263E; font-weight: bold;'>Alle E-Mail-Workflows sind aktiv:</p>
                <ul>
                    <li>Willkommens-E-Mails bei Neuanmeldung</li>
                    <li>Ausleihbestätigungen mit Rückgabefristen</li>
                    <li>Vormerkungs-Benachrichtigungen bei Buchrückgabe</li>
                    <li>Automatische Fristerinnerungen & Mahnungen</li>
                    <li>Passwort-Reset per Sicherheitslink</li>
                    <li>Täglicher Admin-Tagesbericht</li>
                </ul>
            </div>
            <div style='background-color: #f8f2f0; padding: 12px; text-align: center; font-size: 12px; color: #777;'>
                SprachCafé Polnisch e.V. &bull; Standort Pankow &bull; Schulzestr. 1, 13187 Berlin
            </div>
        </div>
"@
        template = "powershell_test"
        source = "hausbibliothek.org"
        timestamp = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ssZ")
        metadata = @{ triggeredBy = "PowerShell Setup Script" }
    } | ConvertTo-Json -Depth 5

    try {
        $Response = Invoke-RestMethod -Uri $WebhookUrl -Method Post -Body $TestPayload -ContentType "application/json; charset=utf-8"
        Write-Host "✅ Test-E-Mail erfolgreich an Webhook übermittelt!" -ForegroundColor Green
        Write-Host "Empfänger: $Recipient" -ForegroundColor Green
    } catch {
        Write-Host "❌ Fehler beim Senden an den Webhook: $_" -ForegroundColor Red
    }

    # -------------------------------------------------------------
    # 3. CONFIGURE SERVER ENVIRONMENT
    # -------------------------------------------------------------
    Write-Host ""
    Write-Host "[3/3] Server-Konfiguration:" -ForegroundColor Cyan
    $EnvLine = "POWER_AUTOMATE_MAIL_WEBHOOK_URL=$WebhookUrl"
    Write-Host "Trage folgende Zeile in die .env-Datei des Backends ein:" -ForegroundColor White
    Write-Host "  $EnvLine" -ForegroundColor Green

    $EnvPath = Join-Path $PSScriptRoot "..\backend\.env"
    if (Test-Path (Split-Path $EnvPath)) {
        Set-Content -Path $EnvPath -Value $EnvLine -Encoding UTF8
        Write-Host "✅ In $EnvPath gespeichert!" -ForegroundColor Green
    }
} else {
    Write-Host ""
    Write-Host "Keine Webhook-URL angegeben. Das System läuft im sicheren MOCK-MODUS (Protokollierung in MySQL-Tabelle 'email_logs')." -ForegroundColor Gray
}

Write-Host ""
Write-Host "Setup-Skript abgeschlossen." -ForegroundColor Cyan
